In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
# importing the dataset
path = "Appliances_energy_prediction_DataSet.csv"
dp = pd.read_csv(path)
df = dp.copy()

In [3]:
pd.set_option("display.max.columns" , None)
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,55.20,7.026667,84.256667,17.200000,41.626667,18.2,48.900000,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,55.20,6.833333,84.063333,17.200000,41.560000,18.2,48.863333,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,55.09,6.560000,83.156667,17.200000,41.433333,18.2,48.730000,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,55.09,6.433333,83.423333,17.133333,41.290000,18.1,48.590000,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,55.09,6.366667,84.893333,17.200000,41.230000,18.1,48.590000,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
#confirming datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [5]:
#checking for null values 
np.sum(df.isnull())

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [6]:
#Accessing Statistical View of data
df.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,19.592106,50.949283,7.910939,54.609083,20.267106,35.388200,22.029107,42.936165,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,1.844623,9.022034,6.090347,31.149806,2.109993,5.114208,1.956162,5.224361,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,15.330000,29.815000,-6.065000,1.000000,15.390000,23.200000,16.306667,29.600000,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,18.277500,45.400000,3.626667,30.025000,18.700000,31.500000,20.790000,39.066667,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,19.390000,49.090000,7.300000,55.290000,20.033333,34.863333,22.100000,42.375000,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,20.619643,53.663333,11.256000,83.226667,21.600000,39.000000,23.390000,46.536000,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,25.795000,96.321667,28.290000,99.900000,26.000000,51.400000,27.230000,58.780000,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

# PreProcessing of DataSet Begins

In [7]:
#from the statistical view, lights have an insignificant impact with zero entries seen in the interquartile range
#further confirming this by evaluating the distribution of values within the column
df.lights.value_counts()

0     15252
10     2212
20     1624
30      559
40       77
50        9
70        1
60        1
Name: lights, dtype: int64

In [8]:
#With 15252 zero entries (light columns) in 19735 rows, the lights column will add no value to the model
# Hence proceeding to drop column
#Also date column will be dropped as this is not a time series problem
df = df.drop(["date","lights"], axis = 1)
df.head(2)

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.7900,19.79,44.73,19.0,45.566667,17.166667,55.2,7.026667,84.256667,17.2,41.626667,18.2,48.900000,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.7225,19.79,44.79,19.0,45.992500,17.166667,55.2,6.833333,84.063333,17.2,41.560000,18.2,48.863333,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195

In [9]:
#it is important our dataset is normalized to a common scale to ensure a good interpretation. this is done by using the min max scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [10]:
#Creating a Dataframe for the scaled df
new_df = pd.DataFrame(scaler.fit_transform(df), columns =df.columns)

#seperating predictor and response variables
pred_vars = new_df.drop(columns =['Appliances'])
response_var = new_df['Appliances']

In [11]:
new_df.corr()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
Appliances,1.000000,0.055447,0.086031,0.120073,-0.060465,0.085060,0.036292,0.040281,0.016965,0.019760,0.006955,0.117638,-0.083178,0.025801,-0.055642,0.039572,-0.094039,0.010010,-0.051462,0.099155,-0.034885,-0.152282,0.087122,0.000230,0.015353,-0.011145,-0.011145
T1,0.055447,1.000000,0.164006,0.836834,-0.002509,0.892402,-0.028550,0.877001,0.097861,0.885247,-0.014782,0.654769,-0.615045,0.838705,0.135182,0.825413,-0.006441,0.844777,0.071756,0.682846,-0.150574,-0.345481,-0.087654,-0.076210,0.571309,-0.006203,-0.006203
RH_1,0.086031,0.164006,1.000000,0.269839,0.797535,0.253230,0.844677,0.106180,0.880359,0.205797,0.303258,0.316141,0.245126,0.021397,0.801122,-0.030053,0.736196,0.115263,0.764001,0.340767,-0.293957,0.274126,0.204932,-0.021057,0.639106,-0.000699,-0.000699
T2,0.120073,0.836834,0.269839,1.000000,-0.165610,0.735245,0.121497,0.762066,0.231563,0.720550,0.029595,0.801186,-0.580372,0.663660,0.229212,0.578191,0.068534,0.675535,0.157346,0.792255,-0.133028,-0.505291,0.052495,-0.069721,0.582602,-0.011087,-0.011087
RH_2,-0.060465,-0.002509,0.797535,-0.165610,1.000000,0.137319,0.678326,-0.047304,0.721435,0.110409,0.250271,-0.009670,0.389933,-0.051422,0.690584,-0.041023,0.679777,0.054544,0.676467,0.033674,-0.255646,0.584911,0.069190,-0.005368,0.499152,0.006275,0.006275
T3,0.085060,0.892402,0.253230,0.735245,0.137319,1.000000,-0.011234,0.852778,0.122737,0.888169,-0.066355,0.686882,-0.647672,0.847374,0.172624,0.795283,0.044427,0.901324,0.134602,0.699417,-0.189974,-0.281718,-0.100776,-0.102310,0.645886,-0.005194,-0.005194
RH_3,0.036292,-0.028550,0.844677,0.121497,0.678326,-0.011234,1.000000,-0.140457,0.898978,-0.050062,0.375422,0.076833,0.514912,-0.250090,0.832685,-0.283228,0.828822,-0.195270,0.833538,0.118207,-0.233274,0.356192,0.263188,0.017041,0.414387,-0.000477,-0.000477
T4,0.040281,0.877001,0.106180,0.762066,-0.047304,0.852778,-0.140457,1.000000,-0.048650,0.871813,-0.076489,0.652350,-0.703149,0.877763,0.043527,0.796256,-0.095192,0.889439,-0.025549,0.663478,-0.075292,-0.388602,-0.185747,-0.104768,0.519471,-0.001815,-0.001815
RH_4,0.016965,0.097861,0.880359,0.231563,0.721435,0.122737,0.898978,-0.048650,1.000000,0.091812,0.352591,0.259047,0.392178,-0.131204,0.894301,-0.167066,0.847259,-0.044518,0.856591,0.293289,-0.250748,0.336813,0.300192,0.002636,0.616509,-0.001787,-0.001787
T5,0.019760,0.885247,0.205797,0.720550,0.110409,0.888169,-0.050062,0.871813,0.091812,1.000000,0.032786,0.629161,-0.632384,0.870624,0.148905,0.824981,0.016388,0.911055,0.072308,0.651321,-0.170999,-0.273953,-0.145011,-0.084164,0.588362,-0.005490,-0.005490
RH_5,0.006955,-0.014782,0.303258,0.029595,0.250271,-0.066355,0.375422,-0.076489,0.352591,0.032786,1.000000,-0.078337,0.263797,-0.142823,0.325808,-0.086991,0.359840,-0.138509,0.272197,-0.053126,-0.119327,0.185941,0.082044,-0.013133,0.078175,-0.011056,-0.011056
T6,0.117638,0.654769,0.316141,0.801186,-0.009670,0.686882,0.076833,0.652350,0.259047,0.629161,-0.078337,1.000000,-0.672137,0.619085,0.256077,0.482836,0.073721,0.667177,0.184424,0.974787,-0.141643,-0.569119,0.169185,-0.081313,0.764242,-0.015086,-0.015086
RH_6,-0.083178,-0.615045,0.245126,-0.580372,0.389933,-0.647672,0.514912,-0.703149,0.392178,-0.632384,0.263797,-0.672137,1.000000,-0.753973,0.357222,-0.665869,0.489580,-0.738940,0.391943,-0.641572,-0.065814,0.718587,0.098317,0.108705,-0.260417,0.011671,0.011671
T7,0.025801,0.838705,0.021397,0.663660,-0.051422,0.847374,-0.250090,0.877763,-0.131204,0.870624,-0.142823,0.619085,-0.753973,1.000000,-0.033948,0.882123,-0.209961,0.944776,-0.077690,0.631293,-0.097724,-0.411213,-0.185892,-0.110089,0.466625,-0.003900,-0.003900
RH_7,-0.055642,0.135182,0.801122,0.229212,0.690584,0.172624,0.832685,0.043527,0.894301,0.148905,0.325808,0.256077,0.357222,-0.033948,1.000000,-0.124102,0.883984,0.028055,0.858686,0.294199,-0.265850,0.378519,0.212979,-0.007184,0.641857,0.001820,0.001820
T8,0.039572,0.825413,-0.030053,0.578191,-0.041023,0.795283,-0.283228,0.796256,-0.167066,0.824981,-0.086991,0.482836,-0.665869,0.882123,-0.124102,1.000000,-0.209532,0.869338,-0.156820,0.502842,-0.162855,-0.300438,-0.218876,-0.060098,0.391810,-0.003210,-0.003210
RH_8,-0.094039,-0.006441,0.736196,0.068534,0.679777,0.044427,0.828822,-0.095192,0.847259,0.016388,0.359840,0.073721,0.489580,-0.209961,0.883984,-0.209532,1.000000,-0.113014,0.855812,0.117141,-0.225591,0.487355,0.202380,0.046178,0.501775,0.004480,0.004480
T9,0.010010,0.844777,0.115263,0.675535,0.054544,0.901324,-0.195270,0.889439,-0.044518,0.911055,-0.138509,0.667177,-0.738940,0.944776,0.028055,0.869338,-0.113014,1.000000,-0.008683,0.668220,-0.156828,-0.318848,-0.177756,-0.103915,0.581483,-0.001227,-0.001227
RH_9,-0.051462,0.071756,0.764001,0.157346,0.676467,0.134602,0.833538,-0.025549,0.856591,0.072308,0.272197,0.184424,0.391943,-0.077690,0.858686,-0.156820,0.855812,-0.008683,1.000000,0.223270,-0.183739,0.359377,0.238655,0.008667,0.540328,-0.002955,-0.002955
T_out,0.099155,0.682846,0.340767,0.792255,0.033674,0.699417,0.118207,0.663478,0.293289,0.651321,-0.053126,0.974787,-0.641572,0.631293,0.294199,0.502842,0.117141,0.668220,0.223270,1.000000,-0.143249,-0.574197,0.192936,-0.077367,0.790661,-0.015216,-0.015216
Press_mm_hg,-0.034885,-0.150574,-0.293957,-0.133028,-0.255646,-0.189974,-0.233274,-0.075292,-0.250748,-0.170999,-0.119327,-0.141643,-0.065814,-0.097724,-0.265850,-0.162855,-0.225591,-0.156828,-0.183739,-0.143249,1.000000,-0.092017,-0.235032,0.040315,-0.244098,0.000699,0.000699
RH_out,-0.152282,-0.345481,0.274126,-0.505291,0.584911,-0.281718,0.356192,-0.388602,0.336813,-0.273953,0.185941,-0.569119,0.718587,-0.411213,0.378519,-0.300438,0.487355,-0.318848,0.359377,-0.574197,-0.092017,1.000000,-0.176458,0.083125,0.036506,0.020441,0.020441
Windspeed,0.087122,-0.087654,0.204932,0.052495,0.069190,-0.100776,0.263188,-0.185747,0.300192,-0.145011,0.082044,0.169185,0.098317,-0.185892,0.212979,-0.218876,0.202380,-0.177756,0.238655,0.192936,-0.235032,-0.176458,1.000000,-0.007516,0.125972,-0.011342,-0.011342
Visibility,0.000230,-0.076210,-0.021057,-0.069721,-0.005368,-0.102310,0.017041,-0.104768,0.002636,-0.084164,-0.013133,-0.081313,0.108705,-0.110089,-0.007184,-0.060098,0.046178,-0.103915,0.008667,-0.077367,0.040315,0.083125,-0.007516,1.000000,-0.042190,-0.005889,-0.005889
Tdewpoint,0.015353,0.571309,0.639106,0.582602,0.499152,0.645886,0.414387,0.519471,0.616509,0.588362,0.078175,0.764242,-0.260417,0.466625,0.641857,0.391810,0.501775,0.581483,0.540328,0.790661,-0.244098,0.036506,0.125972,-0.042190,1.000000,-0.003943,-0.003943
rv1,-0.011145,-0.006203,-0.000699,-0.011087,0.006275,-0.005194,-0.000477,-0.001815,-0.001787,-0.005490,-0.011056,-0.015086,0.011671,-0.003900,0.001820,-0.003210,0.004480,-0.001227,-0.002955,-0.015216,0.000699,0.020441,-0.011342,-0.005889,-0.003943,1.000000,1.000000
rv2,-0.011145,-0.006203,-0.000699,-0.011087,0.006275,-0.005194,-0.000477,-0.001815,-0.001787,-0.005490,-0.011056,-0.015086,0.011671,-0.003900,0.001820,-0.003210,0.004480,-0.001227,-0.002955,-0.015216,0.000699,0.020441,-0.011342,-0.005889,-0.003943,1.000000,1.000000

# QUESTION 12 : FIT A LINEAR MODEL BETWEEN T2 AND T6. WHAT IS THE R^2

In [12]:
train_x = df[['T2']]
train_y = df[['T6']]

#  splitting our dataset into the training and testing 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_x, train_y, test_size = 0.3, random_state = 42)

#importing linear regression
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

#fitting the model to the training dataset
linear_model.fit(x_train, y_train)

#obtaining predictions
predicted_values = linear_model.predict(x_test)


#R-Squared(Coefficient of Determination)
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_values)
round(r2_score, 3)

0.643

# QUESTION 13: FIND THE MEA

In [13]:
#importing linear regression
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

# now, splitting our dataset into the training and testing 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(pred_vars, response_var, test_size = 0.3, random_state = 42)

#fitting the model to the training dataset
linear_model.fit(x_train, y_train)

#obtaining predictions
predicted_values = linear_model.predict(x_test)

In [14]:
#evaluating regression performance using appropriate metrics
#Mean Absolute Error(MAE)
from sklearn.metrics import mean_absolute_error
mae =mean_absolute_error(y_test, predicted_values)
round(mae, 3)

0.05

# QUESTION 14 :FIND THE RSS

In [16]:
#Residual sum of squares(RSS)
rss = np.sum(np.square(y_test - predicted_values))
round(rss, 3)

45.348

# QUESTION 15: FIND THE RMSE

In [18]:
##Root mean squared error(RMSE)
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test , predicted_values))
round(rmse, 3)

0.088

# QUESTION 16: FIND THE R2_SCORE

In [19]:
#R-Squared(Coefficient of Determination)
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_values)
round(r2_score, 3)

0.149

# QUESTION 17:DETERMINE THE FEATURE WEIGHTS FOR THE LINEAR MODEL

In [27]:
 weights = pd.Series(linear_model.coef_, x_train.columns).sort_values()
feature_weights = weights.reset_index()
feature_weights.columns = ['Features', 'weight']
min_feat = feature_weights['weight'].min()
max_feat = feature_weights['weight'].max()

feature_weights[feature_weights['weight'] == min_feat]
#feature_weights[feature_weights['weight'] == max_feat]

  Features    weight
0     RH_2 -0.456698

# QUESTION 18: TRAIN A RIDGE MODEL WITH AN ALPHA OF 0.4 AND GET THE RMSE

In [28]:
#ridge regression
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
#fitting the model to the training dataset
ridge_reg.fit(x_train, y_train)
#obtaining predictions
predicted_reg = ridge_reg.predict(x_test)

In [30]:
#evaluating regression performance using rmse metric
rmse = np.sqrt(mean_squared_error(y_test, predicted_reg))
round(rmse, 3)

0.088

# QUESTION 19: TRAIN A LASSO MODEL HAVING AN ALPHA OF 0.001 AND OBTAIN THE NEW FEATURE WEIGHTS

In [35]:
#feature selection and lasso regression
from  sklearn.linear_model import Lasso
#defining the model and alpha
lasso_reg = Lasso(alpha = 0.001)
#fitting the model to the training dataset
lasso_reg.fit(x_train, y_train)
#obtaining predictions
predicted_lasso = lasso_reg.predict(x_test)

feature_weights = lasso_reg.coef_

weights_value = []
for i in feature_weights:
    if i !=0:
        weights_value.append(i)
weight_value_count = len(weights_value)
weight_value_count

4

# QUESTION 20: DETERMINE THE NEW RMSE

In [38]:
##Root mean squared error(RMSE)
rmse = np.sqrt(mean_squared_error(y_test, predicted_lasso))
round(rmse, 3)

0.094